CREATE TABLE `MONSTER` (
	`ID` int(10) UNSIGNED NULL DEFAULT NULL,
	`NAME` VARCHAR(50) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(5000) NULL DEFAULT NULL,
	`ARMOR` int(10) NULL DEFAULT NULL,
	`SPEED` int(10) NULL DEFAULT NULL, 
	`HITPOINTS` int(10) NULL DEFAULT NULL,
	`ID_STATUS` int(10) NULL DEFAULT NULL,
	`ID_SKILLS` int(10) NULL DEFAULT NULL,
	`ID_VULNERABILITIES` int(10) NULL DEFAULT NULL,
	`ID_TALENTS` int(10) NULL DEFAULT NULL,
	`ID_ACTIONS` int(10) NULL DEFAULT NULL
)
ENGINE=InnoDB
;