CREATE TABLE `status` (
	`ID_STATUS` INT(10) UNSIGNED NOT NULL,
	`Strength` INT(3) NULL DEFAULT NULL,
	`Dexterity` INT(3) NULL DEFAULT NULL,
	`Constitution` INT(3) NULL DEFAULT NULL,
	`Intelligence` INT(3) NULL DEFAULT NULL,
	`Wisdom` INT(3) NULL DEFAULT NULL,
	`Charisma` INT(3) NULL DEFAULT NULL,
	`ID_MONSTER` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`ID_STATUS`),
	INDEX `FK_STATUSMONSTER` (`ID_MONSTER`),
	CONSTRAINT `FK_STATUSMONSTER` FOREIGN KEY (`ID_MONSTER`) REFERENCES `monsters` (`id_monster`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
