CREATE TABLE `actions` (
	`ID_ACTION` INT(10) UNSIGNED NOT NULL,
	`NAME` VARCHAR(50) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(5000) NULL DEFAULT NULL,
	`ID_MONSTER` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`ID_ACTION`),
	INDEX `FK_ACTIONMONSTER` (`ID_MONSTER`),
	CONSTRAINT `FK_ACTIONMONSTER` FOREIGN KEY (`ID_MONSTER`) REFERENCES `monsters` (`id_monster`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
