CREATE TABLE `monsters` (
	`ID_MONSTER` INT(10) UNSIGNED NULL DEFAULT NULL,
	`NAME` VARCHAR(50) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(5000) NULL DEFAULT NULL,
	`ARMOR` VARCHAR(50) NULL DEFAULT NULL,
	`SPEED` VARCHAR(20) NULL DEFAULT NULL,
	`HITPOINTS` INT(10) NULL DEFAULT NULL,
	INDEX `index_id_monster` (`ID_MONSTER`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
