CREATE TABLE `talent` (
	`ID_TALENT` INT(10) UNSIGNED NOT NULL,
	`Name` VARCHAR(50) NULL DEFAULT NULL,
	`Description` VARCHAR(5000) NULL DEFAULT NULL,
	`ID_MONSTER` INT(10) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`ID_TALENT`),
	INDEX `FK_TALENTMONSTER` (`ID_MONSTER`),
	CONSTRAINT `FK_TALENTMONSTER` FOREIGN KEY (`ID_MONSTER`) REFERENCES `monsters` (`id_monster`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
